import { Platform } from "react-native";

export type AppThemeName =
  | "pastel"
  | "light"
  | "dark"
  | "focus"
  | "sunset"
  | "ocean"
  | "midnight"
  | "obsidian"
  | "emberNight"
  | "amazonLight"
  | "githubDark"
  | "auroraDark"
  | "voidBlack"
  | "slateSteel"
  | "roseQuartz"
  | "forestMist"
  | "latteCream"
  | "citrusPop"
  | "neonNoir"
  | "royalIndigo"
  | "monochromePro";

type ThemePalette = {
  text: string;
  background: string;
  card: string;
  surface: string;
  tint: string;
  icon: string;
  tabIconDefault: string;
  tabIconSelected: string;
  subtle: string;
  border: string;
  danger: string;
  success: string;
  warning: string;
  statusBar: "light" | "dark";
  navigationTone: "light" | "dark";
};

export const ThemeLabels: Record<AppThemeName, string> = {
  pastel: "Pastel",
  light: "Light",
  dark: "Dark",
  focus: "Focus",
  sunset: "Sunset",
  ocean: "Ocean",
  midnight: "Midnight",
  obsidian: "Obsidian",
  emberNight: "Ember Night",
  amazonLight: "Amazon Light",
  githubDark: "GitHub Dark",
  auroraDark: "Aurora Dark",
  voidBlack: "Void Black",
  slateSteel: "Slate Steel",
  roseQuartz: "Rose Quartz",
  forestMist: "Forest Mist",
  latteCream: "Latte Cream",
  citrusPop: "Citrus Pop",
  neonNoir: "Neon Noir",
  royalIndigo: "Royal Indigo",
  monochromePro: "Monochrome Pro",
};

export const Colors: Record<AppThemeName, ThemePalette> = {
  pastel: {
    text: "#2b2433",
    background: "#fdf6ff",
    card: "#ffffff",
    surface: "#f8f0fb",
    tint: "#c4a8d4",
    icon: "#65566f",
    tabIconDefault: "#7f6f8c",
    tabIconSelected: "#c4a8d4",
    subtle: "#5f526a",
    border: "#e8d8f0",
    danger: "#e07a9b",
    success: "#8dcf9f",
    warning: "#f2b97f",
    statusBar: "dark",
    navigationTone: "light",
  },
  light: {
    text: "#202631",
    background: "#f8fafc",
    card: "#ffffff",
    surface: "#eef2f7",
    tint: "#6c8ef5",
    icon: "#596579",
    tabIconDefault: "#778294",
    tabIconSelected: "#6c8ef5",
    subtle: "#4b5563",
    border: "#dbe3ef",
    danger: "#dc6f7d",
    success: "#5fa97a",
    warning: "#e0a84f",
    statusBar: "dark",
    navigationTone: "light",
  },
  dark: {
    text: "#f3f4f6",
    background: "#121418",
    card: "#1b1f27",
    surface: "#252b36",
    tint: "#8ca8ff",
    icon: "#9aa4b2",
    tabIconDefault: "#657080",
    tabIconSelected: "#8ca8ff",
    subtle: "#b3bcc8",
    border: "#2f3744",
    danger: "#ff8ba0",
    success: "#7ad79d",
    warning: "#f4c27a",
    statusBar: "light",
    navigationTone: "dark",
  },
  focus: {
    text: "#172017",
    background: "#f4f1e8",
    card: "#fffdf7",
    surface: "#ece6d7",
    tint: "#6f8a56",
    icon: "#5c6755",
    tabIconDefault: "#78836c",
    tabIconSelected: "#6f8a56",
    subtle: "#555f4e",
    border: "#ddd5c2",
    danger: "#c96f5d",
    success: "#7aa06a",
    warning: "#c79a4b",
    statusBar: "dark",
    navigationTone: "light",
  },
  sunset: {
    text: "#321d1d",
    background: "#fff4ec",
    card: "#fffdf8",
    surface: "#fde6da",
    tint: "#dd6b4d",
    icon: "#855f52",
    tabIconDefault: "#a07767",
    tabIconSelected: "#dd6b4d",
    subtle: "#6a4b43",
    border: "#f1d1c4",
    danger: "#d95d70",
    success: "#7aa46d",
    warning: "#e7a44d",
    statusBar: "dark",
    navigationTone: "light",
  },
  ocean: {
    text: "#0f2a36",
    background: "#eefbff",
    card: "#ffffff",
    surface: "#dff2f6",
    tint: "#2d8fa3",
    icon: "#467080",
    tabIconDefault: "#6f929c",
    tabIconSelected: "#2d8fa3",
    subtle: "#3e6671",
    border: "#c9e6ed",
    danger: "#d56f7b",
    success: "#58a68b",
    warning: "#d7a347",
    statusBar: "dark",
    navigationTone: "light",
  },
  midnight: {
    text: "#f4f7ff",
    background: "#0c1220",
    card: "#141d31",
    surface: "#1d2942",
    tint: "#67d1ff",
    icon: "#8aa0c0",
    tabIconDefault: "#53637d",
    tabIconSelected: "#67d1ff",
    subtle: "#b3c1d8",
    border: "#25324b",
    danger: "#ff8ca2",
    success: "#6fd3a7",
    warning: "#f0c36f",
    statusBar: "light",
    navigationTone: "dark",
  },
  obsidian: {
    text: "#f6f1e8",
    background: "#070707",
    card: "#111111",
    surface: "#1c1a17",
    tint: "#d7b46a",
    icon: "#9a9286",
    tabIconDefault: "#676059",
    tabIconSelected: "#d7b46a",
    subtle: "#b7aa9a",
    border: "#2a2620",
    danger: "#ff7d7d",
    success: "#87d99a",
    warning: "#f0bd62",
    statusBar: "light",
    navigationTone: "dark",
  },
  emberNight: {
    text: "#fff3eb",
    background: "#150c0a",
    card: "#22130f",
    surface: "#321c16",
    tint: "#ff8a4c",
    icon: "#b78978",
    tabIconDefault: "#7e5b50",
    tabIconSelected: "#ff8a4c",
    subtle: "#d4ab9b",
    border: "#43271f",
    danger: "#ff7a93",
    success: "#8ed69d",
    warning: "#ffc46b",
    statusBar: "light",
    navigationTone: "dark",
  },
  amazonLight: {
    text: "#17202a",
    background: "#f3f4f6",
    card: "#ffffff",
    surface: "#e7eef3",
    tint: "#ff9900",
    icon: "#46515c",
    tabIconDefault: "#5f6872",
    tabIconSelected: "#ff9900",
    subtle: "#475563",
    border: "#d5dde5",
    danger: "#c7511f",
    success: "#067d62",
    warning: "#b7791f",
    statusBar: "dark",
    navigationTone: "light",
  },
  githubDark: {
    text: "#f0f6fc",
    background: "#0d1117",
    card: "#161b22",
    surface: "#21262d",
    tint: "#58a6ff",
    icon: "#8b949e",
    tabIconDefault: "#6e7681",
    tabIconSelected: "#58a6ff",
    subtle: "#8b949e",
    border: "#30363d",
    danger: "#ff7b72",
    success: "#3fb950",
    warning: "#d29922",
    statusBar: "light",
    navigationTone: "dark",
  },
  auroraDark: {
    text: "#eef7ff",
    background: "#07111f",
    card: "#0d1b2e",
    surface: "#132943",
    tint: "#7dd3fc",
    icon: "#92a8c4",
    tabIconDefault: "#5e728c",
    tabIconSelected: "#7dd3fc",
    subtle: "#b5c7dc",
    border: "#203651",
    danger: "#fb7185",
    success: "#34d399",
    warning: "#fbbf24",
    statusBar: "light",
    navigationTone: "dark",
  },
  voidBlack: {
    text: "#f7f8f5",
    background: "#020302",
    card: "#0a0d0b",
    surface: "#111712",
    tint: "#9eff6e",
    icon: "#8da28c",
    tabIconDefault: "#576356",
    tabIconSelected: "#9eff6e",
    subtle: "#a8b4a5",
    border: "#1f2a20",
    danger: "#ff6f6f",
    success: "#7cff9e",
    warning: "#ffd166",
    statusBar: "light",
    navigationTone: "dark",
  },
  slateSteel: {
    text: "#edf4fb",
    background: "#111821",
    card: "#192331",
    surface: "#223044",
    tint: "#7db4ff",
    icon: "#94a8be",
    tabIconDefault: "#627384",
    tabIconSelected: "#7db4ff",
    subtle: "#b4c3d2",
    border: "#2d3e52",
    danger: "#ff8d8d",
    success: "#77d8a1",
    warning: "#f3c76f",
    statusBar: "light",
    navigationTone: "dark",
  },
  roseQuartz: {
    text: "#32202a",
    background: "#fff7fb",
    card: "#ffffff",
    surface: "#f8e7ef",
    tint: "#d65f93",
    icon: "#755466",
    tabIconDefault: "#947083",
    tabIconSelected: "#d65f93",
    subtle: "#674f5c",
    border: "#efd4df",
    danger: "#d84f68",
    success: "#5fae8a",
    warning: "#d99a42",
    statusBar: "dark",
    navigationTone: "light",
  },
  forestMist: {
    text: "#17271f",
    background: "#f3fbf4",
    card: "#ffffff",
    surface: "#e5f3e8",
    tint: "#3f8f62",
    icon: "#4f6b5b",
    tabIconDefault: "#6e8978",
    tabIconSelected: "#3f8f62",
    subtle: "#4d5f52",
    border: "#cfe5d5",
    danger: "#c85f66",
    success: "#3f9f6a",
    warning: "#c78a36",
    statusBar: "dark",
    navigationTone: "light",
  },
  latteCream: {
    text: "#2f231a",
    background: "#fbf4ea",
    card: "#fffaf2",
    surface: "#f1e4d2",
    tint: "#b97745",
    icon: "#735c49",
    tabIconDefault: "#8e7865",
    tabIconSelected: "#b97745",
    subtle: "#665342",
    border: "#e5d3be",
    danger: "#c45d54",
    success: "#6d9f72",
    warning: "#c6943f",
    statusBar: "dark",
    navigationTone: "light",
  },
  citrusPop: {
    text: "#17271e",
    background: "#fffdf2",
    card: "#ffffff",
    surface: "#f5f0ca",
    tint: "#f7b801",
    icon: "#516348",
    tabIconDefault: "#758158",
    tabIconSelected: "#f7b801",
    subtle: "#4f5c45",
    border: "#e9e0a9",
    danger: "#e45757",
    success: "#2f9e72",
    warning: "#f77f00",
    statusBar: "dark",
    navigationTone: "light",
  },
  neonNoir: {
    text: "#f5fbff",
    background: "#050711",
    card: "#0d1020",
    surface: "#161a2e",
    tint: "#00e5ff",
    icon: "#8391b3",
    tabIconDefault: "#4b587a",
    tabIconSelected: "#00e5ff",
    subtle: "#a7b3d1",
    border: "#252b45",
    danger: "#ff4d8d",
    success: "#37f0a3",
    warning: "#ffe66d",
    statusBar: "light",
    navigationTone: "dark",
  },
  royalIndigo: {
    text: "#f6f0ff",
    background: "#130b2a",
    card: "#1d123c",
    surface: "#2a1b52",
    tint: "#b794f6",
    icon: "#a99ac7",
    tabIconDefault: "#6e5e91",
    tabIconSelected: "#b794f6",
    subtle: "#c9bbe6",
    border: "#3a2a66",
    danger: "#ff7aa8",
    success: "#65d6a6",
    warning: "#f7c56f",
    statusBar: "light",
    navigationTone: "dark",
  },
  monochromePro: {
    text: "#f6f7f9",
    background: "#0b0c0e",
    card: "#15171a",
    surface: "#202327",
    tint: "#f2f4f8",
    icon: "#a0a7b1",
    tabIconDefault: "#686f78",
    tabIconSelected: "#f2f4f8",
    subtle: "#b3bac5",
    border: "#2d3137",
    danger: "#ff6b6b",
    success: "#89d185",
    warning: "#d9b36a",
    statusBar: "light",
    navigationTone: "dark",
  },
};

export const Fonts = Platform.select({
  ios: {
    sans: "system-ui",
    serif: "ui-serif",
    rounded: "ui-rounded",
    mono: "ui-monospace",
  },
  default: {
    sans: "normal",
    serif: "serif",
    rounded: "normal",
    mono: "monospace",
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
